version: '3'

networks:
  nginx-php:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: shop_system_nginx
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - nginx-php

  php:
    container_name: shop_system_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "2000:2000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php

  db:
    image: mysql:8
    container_name: shop_system_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: shop_system
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_HOST: localhost
