version: '3'

networks:
  nginx-php:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: shop_system_nginx
    ports:
      - "1000:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - nginx-php

  php:
    container_name: shop_system_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "2000:2000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php
