parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity'
            - '../src/Kernel.php'

#    App\Application\ValueResolver\OrdersController\CreateOrderValueResolver:
#        tags:
#            - { name: controller.argument_value_resolver, priority: 150 }

    App\Application\ValueResolver\ProductsController\CreateProductValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }