parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity'
            - '../src/Kernel.php'

    App\Domain\Repository\OrderRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\OrderRepository'
    App\Domain\Repository\ProductRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\ProductRepository'
    App\Domain\Repository\UserRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\UserRepository'
