parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity'
            - '../src/Kernel.php'

    App\Application\Query\QueryHandlerInterface:
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    App\Application\Command\CommandHandlerInterface:
        tags:
            - { name: messenger.message_handler, bus: command.bus }
