parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity'
            - '../src/Kernel.php'

    App\Domain\Repository\OrderRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\OrderRepository'
    App\Domain\Repository\ProductRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\ProductRepository'
    App\Domain\Repository\UserRepositoryInterface:
        class: 'App\Infrastructure\Doctrine\Repository\UserRepository'

    App\Application\EventSubscriber\AuthenticationSuccessSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }

    App\Application\EventSubscriber\AuthenticationFailureSubscriber:
        tags:
            - { name: kernel.event_subscriber }
